# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              MS&E 233. Game Theory, Data Science and AI
description:        Website for Stanford course on Game Theory, Data Science and AI

# Site subpath, e.g. /blog
baseurl:            "/spring24"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url :               "https://stanford-msande233.github.io"

# Site logo, image or text
brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           MS&E 233. Game Theory, Data Science and AI      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Vasilis Syrgkanis
    github:     vsyrgkanis   # Github username for avatar


github_info:
    username:          stanford-msande233/spring24                # Github location of the course
    branch:            master               # branch where github page is hosted - see settings
    website-repo:      spring24      # name of this current repo, contains course site files
    course-repo:       spring24   # location of course content files like data, textbook, labs, etc.

index:
    title: Game Theory, Data Science and AI 
    image: 
    subtitle: The course will explore applied topics at the intersection of game theory, data science and artificial intelligence.
    


header:
- title: Syllabus
  url: /
  
- title: Course Schedule
  url: schedule/

- title: Resources
  url: resources/


footer:
- title: Home
  url: /

- title: Course Schedule
  url: /schedule/


info: 
 program_title: Management Science and Engineering
 program_website: 
 course_title: Game Theory, Data Science and AI
 course_number: MS&E 233
 course_level: Graduate
 course_website: 
 course_start_end_dates: Apr 1st - Jun 5th, 2024
 course_prerequisites: None
 class_meets_when: Tue-Thu 3.00-4.20
 class_meets_where: Shriram 104 

instructor:
-  name: Vasilis Syrgkanis
   title: Assistant Professor
   email: vsyrgk@stanford.edu
   website_url: https://vsyrgkanis.com/
   office_hours_times: 
   office_hours_location: Huang 252
   office_hours_app_url:  
   github_url: 
   twitter_url: 
   scholar_url: 
   linked_in_url:



textbooks:
- title: Lecture Notes on Algorithmic Game Theory
  authors: Tim Roughgarden
  edition: Free Online
  link: https://timroughgarden.org/f13/f13.pdf
  required (y/n): n
- title: AI, Games and Markets
  authors: Christian Kroer
  edition: Free Online
  link: https://www.columbia.edu/~ck2945/files/main_ai_games_markets.pdf
  required (y/n): n
- title: Algorithmic Game Theory
  authors: Noam Nisan, Tim Roughgarden, Eva Tardos, Vijay Vazirani
  edition: Free Online
  link: https://www.cs.cmu.edu/~sandholm/cs15-892F13/algorithmic-game-theory.pdf
  required (y/n): n
- title: Online Learning and Online Convex Optimization
  authors: Shai Shalev-Shwartz
  edition: Not Required
  link: https://www.cs.huji.ac.il/~shais/papers/OLsurvey.pdf
  required (y/n): n




# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    jesse:
        name:       Vasilis Syrgkanis
        github:     vsyrgkanis    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      
    linkedin:       
    pinterest:
    twitter:        
    vimeo:          
    youtube:        

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://www.youtube.com/watch?v=WUAcN9UCnbU">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   G-L8SNR4LLEB

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "layouts/datasets/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true



course_url: "https://stanford-msande233.github.io/spring24"

